# Generated by Django 3.2.8 on 2022-01-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220123_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answered_all',
            field=models.BooleanField(default=False),
        ),
    ]
