# Generated by Django 3.2.8 on 2022-01-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_answered_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answered_all',
        ),
        migrations.AddField(
            model_name='user',
            name='categories_answered',
            field=models.IntegerField(default=0),
        ),
    ]
