# Generated by Django 4.0 on 2022-02-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='category_of_questionnaire',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
