# Generated by Django 3.2.8 on 2022-01-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.TextField(),
        ),
    ]
