# Generated by Django 4.0 on 2022-02-08 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220123_0037'),
        ('questionnaire', '0002_alter_response_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='responder',
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False)),
                ('provided_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
            ],
        ),
    ]
