# Generated by Django 4.0 on 2022-02-08 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_remove_question_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question'),
        ),
    ]
