# Generated by Django 4.0 on 2022-02-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archived',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
