# Generated by Django 4.0 on 2021-12-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='outfrnt_task',
            field=models.BooleanField(default=False),
        ),
    ]
