# Generated by Django 3.2.8 on 2022-01-14 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0004_remove_archivedevents_outfrnt_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivedEvents',
            new_name='Archived',
        ),
    ]
